exclude: ^(venv/|htmlcov/|\.git/|\.pytest_cache/|__pycache__/)
repos:
  # Basic pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^venv/
      - id: end-of-file-fixer
        exclude: ^venv/
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: check-ast
        exclude: ^venv/
      - id: check-docstring-first
        exclude: ^venv/
      - id: debug-statements
        exclude: ^venv/
      - id: mixed-line-ending
        exclude: ^venv/
      - id: requirements-txt-fixer

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "100"]
        exclude: ^venv/

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.12
        args: ["--line-length", "100"]
        exclude: ^venv/

  # Python linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length", "100", "--extend-ignore", "E203,W503"]
        exclude: ^venv/

  # Python type checking (disabled due to architecture issues)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.7.1
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-requests]
  #       args: ["--ignore-missing-imports"]
  #       exclude: ^venv/

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        exclude: ^venv/

  # Documentation style
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ["--convention", "google"]
        exclude: ^venv/

  # Commit message formatting
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
