# Production Alert Rules for Academic Agent
# These rules define critical alerts for production monitoring

groups:
- name: academic-agent-critical
  rules:
  - alert: ApplicationDown
    expr: up{job="academic-agent"} == 0
    for: 1m
    labels:
      severity: critical
      service: academic-agent
      environment: production
    annotations:
      summary: "Academic Agent application is down"
      description: "Academic Agent application has been down for more than 1 minute. Instance: {{ $labels.instance }}"
      runbook_url: "https://wiki.company.com/runbooks/academic-agent-down"

  - alert: DatabaseConnectionFailed
    expr: up{job="postgres"} == 0
    for: 30s
    labels:
      severity: critical
      service: database
      environment: production
    annotations:
      summary: "PostgreSQL database is unreachable"
      description: "PostgreSQL database connection failed. This will cause application failures."
      runbook_url: "https://wiki.company.com/runbooks/database-connection-failed"

  - alert: RedisConnectionFailed
    expr: up{job="redis"} == 0
    for: 1m
    labels:
      severity: warning
      service: cache
      environment: production
    annotations:
      summary: "Redis cache is unreachable"
      description: "Redis cache connection failed. Application may experience degraded performance."
      runbook_url: "https://wiki.company.com/runbooks/redis-connection-failed"

- name: academic-agent-performance
  rules:
  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
    for: 5m
    labels:
      severity: warning
      service: system
      environment: production
    annotations:
      summary: "High memory usage detected"
      description: "Memory usage is above 90% for more than 5 minutes. Current usage: {{ $value | humanizePercentage }}"
      runbook_url: "https://wiki.company.com/runbooks/high-memory-usage"

  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 10m
    labels:
      severity: warning
      service: system
      environment: production
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is above 80% for more than 10 minutes. Current usage: {{ $value }}%"
      runbook_url: "https://wiki.company.com/runbooks/high-cpu-usage"

  - alert: DiskSpaceLow
    expr: (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) / node_filesystem_size_bytes{fstype!="tmpfs"} > 0.85
    for: 5m
    labels:
      severity: warning
      service: system
      environment: production
    annotations:
      summary: "Disk space running low"
      description: "Disk usage is above 85% on {{ $labels.device }}. Current usage: {{ $value | humanizePercentage }}"
      runbook_url: "https://wiki.company.com/runbooks/disk-space-low"

  - alert: DiskSpaceCritical
    expr: (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) / node_filesystem_size_bytes{fstype!="tmpfs"} > 0.95
    for: 1m
    labels:
      severity: critical
      service: system
      environment: production
    annotations:
      summary: "Disk space critically low"
      description: "Disk usage is above 95% on {{ $labels.device }}. Immediate action required!"
      runbook_url: "https://wiki.company.com/runbooks/disk-space-critical"

- name: academic-agent-application
  rules:
  - alert: HighErrorRate
    expr: rate(academic_agent_errors_total[5m]) > 0.1
    for: 2m
    labels:
      severity: warning
      service: academic-agent
      environment: production
    annotations:
      summary: "High error rate detected"
      description: "Error rate is above 10% for the last 5 minutes. Current rate: {{ $value | humanizePercentage }}"
      runbook_url: "https://wiki.company.com/runbooks/high-error-rate"

  - alert: LowQualityScores
    expr: avg(academic_agent_quality_score) < 0.7
    for: 10m
    labels:
      severity: warning
      service: academic-agent
      environment: production
    annotations:
      summary: "Quality scores are declining"
      description: "Average quality score has been below 0.7 for 10 minutes. Current score: {{ $value }}"
      runbook_url: "https://wiki.company.com/runbooks/low-quality-scores"

  - alert: ProcessingTimeout
    expr: increase(academic_agent_processing_timeouts_total[5m]) > 5
    for: 1m
    labels:
      severity: warning
      service: academic-agent
      environment: production
    annotations:
      summary: "Multiple processing timeouts"
      description: "More than 5 processing timeouts in the last 5 minutes"
      runbook_url: "https://wiki.company.com/runbooks/processing-timeouts"

  - alert: TooManyRestarts
    expr: increase(kube_pod_container_status_restarts_total{container="academic-agent"}[1h]) > 3
    for: 1m
    labels:
      severity: warning
      service: academic-agent
      environment: production
    annotations:
      summary: "Academic Agent container restarting frequently"
      description: "Academic Agent container has restarted {{ $value }} times in the last hour"
      runbook_url: "https://wiki.company.com/runbooks/container-restarts"

- name: academic-agent-database
  rules:
  - alert: DatabaseHighConnections
    expr: pg_stat_database_numbackends{datname="academic_agent_prod"} > 80
    for: 5m
    labels:
      severity: warning
      service: database
      environment: production
    annotations:
      summary: "High number of database connections"
      description: "Database has {{ $value }} active connections (> 80)"
      runbook_url: "https://wiki.company.com/runbooks/high-db-connections"

  - alert: DatabaseSlowQueries
    expr: pg_stat_activity_max_tx_duration{datname="academic_agent_prod"} > 300
    for: 2m
    labels:
      severity: warning
      service: database
      environment: production
    annotations:
      summary: "Slow database queries detected"
      description: "Longest running query has been active for {{ $value }} seconds"
      runbook_url: "https://wiki.company.com/runbooks/slow-queries"

  - alert: DatabaseReplicationLag
    expr: pg_replication_lag > 60
    for: 5m
    labels:
      severity: warning
      service: database
      environment: production
    annotations:
      summary: "Database replication lag"
      description: "Database replication is lagging by {{ $value }} seconds"
      runbook_url: "https://wiki.company.com/runbooks/replication-lag"

- name: academic-agent-network
  rules:
  - alert: HighNetworkErrors
    expr: rate(node_network_receive_errs_total[5m]) > 0.01
    for: 5m
    labels:
      severity: warning
      service: network
      environment: production
    annotations:
      summary: "High network error rate"
      description: "Network error rate is above 1% on interface {{ $labels.device }}"
      runbook_url: "https://wiki.company.com/runbooks/network-errors"

  - alert: LoadBalancerUnhealthy
    expr: sum(up{job="kubernetes-service-endpoints"}) / count(up{job="kubernetes-service-endpoints"}) < 0.5
    for: 2m
    labels:
      severity: critical
      service: load-balancer
      environment: production
    annotations:
      summary: "Load balancer has too many unhealthy targets"
      description: "Less than 50% of load balancer targets are healthy"
      runbook_url: "https://wiki.company.com/runbooks/unhealthy-targets"

- name: academic-agent-security
  rules:
  - alert: TooManyFailedLogins
    expr: increase(academic_agent_failed_logins_total[5m]) > 20
    for: 1m
    labels:
      severity: warning
      service: security
      environment: production
    annotations:
      summary: "High number of failed login attempts"
      description: "More than 20 failed login attempts in the last 5 minutes"
      runbook_url: "https://wiki.company.com/runbooks/failed-logins"

  - alert: UnauthorizedAPIAccess
    expr: increase(academic_agent_unauthorized_requests_total[5m]) > 10
    for: 1m
    labels:
      severity: warning
      service: security
      environment: production
    annotations:
      summary: "High number of unauthorized API requests"
      description: "More than 10 unauthorized API requests in the last 5 minutes"
      runbook_url: "https://wiki.company.com/runbooks/unauthorized-access"

  - alert: SSLCertificateExpiringSoon
    expr: (ssl_certificate_expiry_seconds - time()) / 86400 < 30
    for: 1h
    labels:
      severity: warning
      service: security
      environment: production
    annotations:
      summary: "SSL certificate expiring soon"
      description: "SSL certificate will expire in {{ $value }} days"
      runbook_url: "https://wiki.company.com/runbooks/ssl-renewal"

  - alert: SSLCertificateExpired
    expr: ssl_certificate_expiry_seconds - time() < 0
    for: 1m
    labels:
      severity: critical
      service: security
      environment: production
    annotations:
      summary: "SSL certificate has expired"
      description: "SSL certificate has expired! Immediate action required."
      runbook_url: "https://wiki.company.com/runbooks/ssl-expired"

- name: academic-agent-business
  rules:
  - alert: LowProcessingThroughput
    expr: rate(academic_agent_documents_processed_total[10m]) < 0.1
    for: 15m
    labels:
      severity: warning
      service: academic-agent
      environment: production
    annotations:
      summary: "Processing throughput is very low"
      description: "Document processing rate has been below 6 per hour for 15 minutes"
      runbook_url: "https://wiki.company.com/runbooks/low-throughput"

  - alert: NoProcessingActivity
    expr: increase(academic_agent_documents_processed_total[30m]) == 0
    for: 30m
    labels:
      severity: critical
      service: academic-agent
      environment: production
    annotations:
      summary: "No document processing activity"
      description: "No documents have been processed in the last 30 minutes"
      runbook_url: "https://wiki.company.com/runbooks/no-processing"

  - alert: QueueBacklog
    expr: academic_agent_queue_size > 100
    for: 10m
    labels:
      severity: warning
      service: academic-agent
      environment: production
    annotations:
      summary: "Large processing queue backlog"
      description: "Processing queue has {{ $value }} items waiting"
      runbook_url: "https://wiki.company.com/runbooks/queue-backlog"

- name: academic-agent-infrastructure
  rules:
  - alert: KubernetesNodeNotReady
    expr: kube_node_status_condition{condition="Ready",status="true"} == 0
    for: 5m
    labels:
      severity: critical
      service: kubernetes
      environment: production
    annotations:
      summary: "Kubernetes node is not ready"
      description: "Node {{ $labels.node }} has been not ready for more than 5 minutes"
      runbook_url: "https://wiki.company.com/runbooks/node-not-ready"

  - alert: KubernetesPodCrashLooping
    expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
    for: 5m
    labels:
      severity: warning
      service: kubernetes
      environment: production
    annotations:
      summary: "Pod is crash looping"
      description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is crash looping"
      runbook_url: "https://wiki.company.com/runbooks/crash-looping"

  - alert: KubernetesPersistentVolumeUsageHigh
    expr: (kubelet_volume_stats_capacity_bytes - kubelet_volume_stats_available_bytes) / kubelet_volume_stats_capacity_bytes > 0.8
    for: 5m
    labels:
      severity: warning
      service: kubernetes
      environment: production
    annotations:
      summary: "Persistent volume usage is high"
      description: "PV {{ $labels.persistentvolumeclaim }} usage is above 80%"
      runbook_url: "https://wiki.company.com/runbooks/pv-usage-high"