apiVersion: v1
kind: Namespace
metadata:
  name: academic-agent
  labels:
    name: academic-agent
    environment: production
    app.kubernetes.io/name: academic-agent
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: academic-agent-quota
  namespace: academic-agent
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "10"
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: academic-agent-limits
  namespace: academic-agent
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container