apiVersion: v1
kind: Secret
metadata:
  name: academic-agent-secrets
  namespace: academic-agent
type: Opaque
stringData:
  SECRET_KEY: "CHANGE_ME_IN_PRODUCTION"
  ENCRYPTION_KEY: "CHANGE_ME_IN_PRODUCTION"
  POSTGRES_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  GRAFANA_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  GRAFANA_DB_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  GROQ_API_KEY: "CHANGE_ME_IN_PRODUCTION"
  OPENAI_API_KEY: "CHANGE_ME_IN_PRODUCTION"
---
apiVersion: v1
kind: Secret
metadata:
  name: academic-agent-db-secrets
  namespace: academic-agent
type: Opaque
stringData:
  username: academic_agent
  password: "CHANGE_ME_IN_PRODUCTION"
  database: academic_agent_prod
---
apiVersion: v1
kind: Secret
metadata:
  name: academic-agent-backup-secrets
  namespace: academic-agent
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "CHANGE_ME_IN_PRODUCTION"
  AWS_SECRET_ACCESS_KEY: "CHANGE_ME_IN_PRODUCTION"
  S3_BUCKET: "academic-agent-backups"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: academic-agent-config
  namespace: academic-agent
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  METRICS_ENABLED: "true"
  PROMETHEUS_PORT: "9090"
  REDIS_URL: "redis://academic-agent-redis:6379/0"
  DATABASE_URL: "postgresql://academic_agent:$(POSTGRES_PASSWORD)@academic-agent-postgres:5432/academic_agent_prod"