# Export System Configuration for Academic Agent
# Provides comprehensive export capabilities with multiple formats

export_system:
  # Default configuration
  defaults:
    output_format: "pdf"  # pdf, html, docx, all
    template_name: "academic"
    image_sizing: "medium"  # small, medium, large, original
    include_diagrams: true
    diagram_format: "png"  # png, svg, text
    quality_level: "high"  # low, medium, high
    consolidate_images: true
    embed_images: true
    resolve_references: true
    optimize_for_print: true
  
  # Template configurations
  templates:
    academic:
      name: "Academic Paper"
      description: "Professional academic template with proper formatting"
      supports_formats: ["pdf", "html", "docx"]
      css_file: "academic.css"
      features:
        - "Professional typography"
        - "Academic citation support"
        - "Table of contents"
        - "Figure captions"
        - "Reference lists"
    
    report:
      name: "Technical Report"
      description: "Technical report template with engineering focus"
      supports_formats: ["pdf", "html"]
      css_file: "report.css"
      features:
        - "Technical diagrams"
        - "Code highlighting"
        - "Appendices"
        - "Executive summary"
    
    presentation:
      name: "Presentation"
      description: "Slide-style presentation template"
      supports_formats: ["html", "pdf"]
      css_file: "presentation.css"
      features:
        - "Slide layouts"
        - "Large fonts"
        - "Minimal text"
        - "Visual emphasis"

  # Image processing settings
  image_processing:
    size_presets:
      small:
        max_width: 400
        max_height: 300
        quality: 70
        format: "jpeg"
      medium:
        max_width: 600
        max_height: 450
        quality: 80
        format: "jpeg"
      large:
        max_width: 800
        max_height: 600
        quality: 85
        format: "png"
      original:
        max_width: null
        max_height: null
        quality: 90
        format: "original"
    
    optimization:
      enable_compression: true
      strip_metadata: true
      progressive_jpeg: true
      png_optimization: true
    
    consolidation:
      create_image_directory: true
      use_content_hashing: true
      deduplicate_images: true
      maintain_aspect_ratio: true

  # Export format settings
  formats:
    pdf:
      engine: "weasyprint"  # weasyprint, reportlab, pandoc
      page_size: "A4"
      margins:
        top: "2cm"
        bottom: "2cm"
        left: "2.5cm"
        right: "2.5cm"
      features:
        page_numbers: true
        table_of_contents: true
        bookmarks: true
        metadata_embedding: true
      optimization:
        font_subsetting: true
        image_compression: true
        remove_unused_objects: true
    
    html:
      engine: "markdown"  # markdown, pandoc, custom
      include_css: true
      standalone: true
      features:
        responsive_design: true
        syntax_highlighting: true
        math_rendering: true  # MathJax support
        interactive_diagrams: true
      optimization:
        minify_css: false
        minify_html: false
        inline_critical_css: true
    
    docx:
      engine: "python-docx"  # python-docx, pandoc
      template_file: null
      features:
        styles_preservation: true
        image_embedding: true
        table_formatting: true
        header_footer: true
      compatibility:
        office_version: "2016"
        track_changes: false

  # Quality validation settings
  quality_validation:
    criteria:
      file_size:
        min_mb: 0.001
        max_mb: 50
        weight: 0.2
      content_structure:
        check_headings: true
        check_images: true
        check_tables: true
        weight: 0.3
      image_quality:
        min_resolution: 72
        max_file_size_mb: 5
        check_formats: true
        weight: 0.2
      reference_integrity:
        check_internal_links: true
        check_image_references: true
        check_citations: true
        weight: 0.2
      format_compliance:
        validate_structure: true
        check_metadata: true
        weight: 0.1
    
    thresholds:
      minimum_score: 0.7
      warning_score: 0.8
      excellent_score: 0.9
    
    actions:
      auto_fix_minor_issues: true
      generate_quality_report: true
      suggest_improvements: true

  # Batch processing settings
  batch_processing:
    max_concurrent_exports: 4
    chunk_size: 10
    timeout_seconds: 300
    retry_failed: true
    max_retries: 2
    
    progress_reporting:
      enabled: true
      update_interval: 5  # seconds
      include_file_details: true
    
    error_handling:
      continue_on_error: true
      collect_error_details: true
      generate_error_report: true

  # Integration settings
  integration:
    study_notes_generator:
      auto_export_generated_notes: true
      default_format: "pdf"
      include_diagrams: true
      use_academic_template: true
    
    pdf_processor:
      export_processed_content: false
      consolidate_with_original: true
      preserve_metadata: true
    
    cms_system:
      register_export_events: true
      store_export_metadata: true
      auto_index_outputs: true

  # Performance settings
  performance:
    memory_limit_mb: 1024
    temp_directory: "/tmp/academic_export"
    cleanup_temp_files: true
    cache_processed_images: true
    cache_duration_hours: 24
    
    monitoring:
      track_processing_time: true
      track_memory_usage: true
      track_file_sizes: true
      generate_performance_reports: true

  # Security settings
  security:
    allowed_file_extensions:
      input: [".md", ".txt", ".json"]
      output: [".pdf", ".html", ".docx"]
      images: [".png", ".jpg", ".jpeg", ".gif", ".svg", ".bmp", ".webp"]
    
    path_validation:
      restrict_to_project: true
      block_system_paths: true
      sanitize_filenames: true
    
    content_filtering:
      strip_dangerous_html: true
      validate_image_formats: true
      check_file_signatures: true

# Logging configuration for export system
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/export_system.log"
  max_size_mb: 10
  backup_count: 5
  
  loggers:
    export_system:
      level: "INFO"
    image_processing:
      level: "DEBUG"
    quality_validation:
      level: "INFO"
    batch_processing:
      level: "INFO"