# Quality Validation System Configuration
# Configuration for ensuring 90% accuracy in PDF-to-markdown conversion

quality_validation:
  # Core validation settings
  accuracy_threshold: 0.9  # Target 90% accuracy
  regression_threshold: 0.05  # 5% drop considered regression
  quality_improvement_threshold: 0.02  # 2% improvement considered significant
  
  # Performance settings
  max_concurrent_tests: 4  # Maximum parallel validation tests
  benchmark_timeout: 300  # 5 minutes timeout per benchmark
  processing_timeout: 120  # 2 minutes timeout for PDF processing
  
  # Directory configuration
  validation_dir: "validation"
  benchmarks_dir: "validation/benchmarks"
  results_dir: "validation/results"
  reports_dir: "validation/reports"
  temp_dir: "validation/temp"
  
  # Accuracy calculation weights
  accuracy_weights:
    content_similarity_weight: 0.4
    structure_similarity_weight: 0.3
    formatting_similarity_weight: 0.2
    metadata_similarity_weight: 0.1
  
  # Quality thresholds by component
  component_thresholds:
    content_accuracy_threshold: 0.85
    structure_accuracy_threshold: 0.85
    formatting_accuracy_threshold: 0.80
    metadata_accuracy_threshold: 0.75
  
  # Benchmark management
  benchmarks:
    auto_create_samples: true
    sample_benchmark_count: 10
    difficulty_distribution:
      easy: 0.3
      medium: 0.5
      hard: 0.2
    content_type_distribution:
      academic: 0.6
      technical: 0.3
      general: 0.1
  
  # Continuous validation
  continuous_validation:
    enabled: true
    schedule: "daily"  # daily, weekly, hourly
    schedule_time: "02:00"  # 2 AM for daily runs
    retry_failed_benchmarks: true
    max_retries: 3
    notification_on_regression: true
    
  # Regression detection
  regression_detection:
    window_days: 7
    min_samples: 3
    sensitivity: "medium"  # low, medium, high
    auto_investigate: true
    create_issues: false  # Create GitHub issues for regressions
    
  # Reporting
  reporting:
    auto_generate_daily: true
    auto_generate_weekly: true
    auto_generate_monthly: true
    report_retention_days: 90
    include_detailed_diffs: true
    include_trend_analysis: true
    export_formats: ["json", "html"]
    
  # Integration settings
  integration:
    prometheus_metrics: true
    grafana_dashboards: true
    slack_notifications: false
    email_notifications: false
    webhook_notifications: false
    
  # Quality improvement
  improvement:
    auto_suggestions: true
    priority_ranking: true
    actionable_recommendations: true
    performance_optimization: true
    
  # Data retention
  data_retention:
    validation_results_days: 90
    benchmark_history_days: 365
    detailed_logs_days: 30
    cleanup_interval_hours: 24

# Monitoring and alerting configuration
monitoring:
  validation_metrics:
    collection_interval_seconds: 30
    export_detailed_metrics: true
    custom_labels:
      environment: "production"
      component: "pdf_processor"
    
  alerts:
    accuracy_drop_threshold: 0.05
    regression_alert_threshold: 2
    performance_degradation_threshold: 0.3
    alert_channels: ["prometheus", "logs"]
    
  dashboards:
    update_interval_minutes: 5
    retention_days: 30
    export_snapshots: true

# Testing and benchmarking
testing:
  test_data:
    sample_pdfs_dir: "test_data/sample_pdfs"
    expected_outputs_dir: "test_data/expected_outputs"
    ground_truth_dir: "test_data/ground_truth"
    
  benchmark_categories:
    academic_papers:
      enabled: true
      weight: 0.4
      accuracy_threshold: 0.92
      sample_count: 15
      
    textbooks:
      enabled: true
      weight: 0.3
      accuracy_threshold: 0.90
      sample_count: 10
      
    technical_documents:
      enabled: true
      weight: 0.2
      accuracy_threshold: 0.88
      sample_count: 8
      
    mixed_content:
      enabled: true
      weight: 0.1
      accuracy_threshold: 0.85
      sample_count: 5
      
  complexity_levels:
    simple:
      characteristics: ["single_column", "basic_formatting", "minimal_images"]
      accuracy_target: 0.95
      processing_time_limit: 30
      
    moderate:
      characteristics: ["multi_column", "complex_formatting", "tables", "images"]
      accuracy_target: 0.90
      processing_time_limit: 60
      
    complex:
      characteristics: ["academic_formulas", "complex_tables", "charts", "multi_language"]
      accuracy_target: 0.85
      processing_time_limit: 120
      
    expert:
      characteristics: ["mathematical_notation", "complex_layouts", "specialized_formatting"]
      accuracy_target: 0.80
      processing_time_limit: 180

# PDF processor configuration
pdf_processor:
  default_settings:
    extract_images: true
    preserve_formatting: true
    handle_tables: true
    process_headers: true
    extract_metadata: true
    
  quality_settings:
    high_accuracy_mode: true
    verbose_logging: true
    detailed_analysis: true
    structure_preservation: true
    
  performance_settings:
    parallel_processing: true
    memory_optimization: true
    cache_enabled: true
    batch_processing: true

# Validation pipeline configuration
pipeline:
  stages:
    - name: "preprocessing"
      enabled: true
      timeout: 30
      retry_count: 2
      
    - name: "pdf_processing"
      enabled: true
      timeout: 120
      retry_count: 3
      
    - name: "accuracy_analysis"
      enabled: true
      timeout: 60
      retry_count: 1
      
    - name: "quality_assessment"
      enabled: true
      timeout: 30
      retry_count: 1
      
    - name: "report_generation"
      enabled: true
      timeout: 30
      retry_count: 1
      
  error_handling:
    fail_fast: false
    continue_on_error: true
    detailed_error_reporting: true
    error_classification: true
    
  optimization:
    cache_intermediate_results: true
    parallel_stage_execution: true
    resource_monitoring: true
    performance_profiling: true

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  handlers:
    console:
      enabled: true
      level: "INFO"
      
    file:
      enabled: true
      level: "DEBUG"
      filename: "validation_system.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5
      
    metrics:
      enabled: true
      level: "INFO"
      filename: "validation_metrics.log"
      
  loggers:
    quality_validation_system:
      level: "DEBUG"
      propagate: false
      
    validation_metrics:
      level: "INFO"
      propagate: false

# Feature flags
features:
  experimental_algorithms: false
  ml_based_comparison: false
  advanced_formatting_analysis: true
  automated_benchmark_generation: false
  real_time_validation: false
  distributed_processing: false

# Security and compliance
security:
  data_encryption: false  # Enable for sensitive documents
  access_control: false
  audit_logging: true
  data_anonymization: false
  
compliance:
  gdpr_compliance: false
  hipaa_compliance: false
  data_retention_policies: true
  audit_trail: true

# Development and debugging
development:
  debug_mode: false
  verbose_output: false
  save_intermediate_files: false
  performance_profiling: false
  memory_tracking: false
  
  test_mode:
    enabled: false
    mock_pdf_processor: false
    deterministic_results: false
    fast_execution: false